#!/bin/sh /etc/rc.common
USE_PROCD=1
START=91
STOP=11

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/python3 /usr/share/mitm/mitm_proxy.py
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
	/usr/libexec/mitm-nft.sh apply
}

stop_service() {
	/usr/libexec/mitm-nft.sh clear
}
