#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=10

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/python3 /usr/share/pktcap/pktcap_server.py
	procd_set_param env PKTCAP_IFACE=br-lan PKTCAP_PORT=7690 PKTCAP_USER=root PKTCAP_PASS=root
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
